# Generated by Django 5.1.2 on 2024-12-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0006_alter_service_contact_info_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
