# Generated by Django 5.1.2 on 2024-12-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0008_alter_listing_image_alter_listing_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
