# Generated by Django 5.1.2 on 2024-12-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0009_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='current_listings/'),
        ),
    ]
