# Generated by Django 5.1.2 on 2024-12-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0010_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Current Listings/'),
        ),
    ]
