# Generated by Django 5.1.2 on 2024-12-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0014_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(max_length=100),
        ),
    ]
