# Generated by Django 5.1.2 on 2024-12-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0015_alter_donation_donor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_email',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(default='M-Pesa', max_length=50),
        ),
    ]
